yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('create/', views.post_create, name='post_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.delete_post, name='delete'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/users/urls.py
# Импортируем из приложения django.contrib.auth нужный view-класс
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordResetView
)
from django.urls import path
from . import views


app_name = 'users'


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
else:

    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', serve,
                kwargs={'document_root': settings.STATIC_ROOT, }),
        re_path(r'^media/(?P<path>.*)$', serve,
                kwargs={'document_root': settings.MEDIA_ROOT, }),
    ]

yatube/templates/includes/article.html
<!DOCTYPE html>
{% load thumbnail %}

<article>
  <ul class="list-group">
    <li class="list-group-item list-group-item-action list-group-item-secondary">

      {% if post.author.get_full_name %}
        Автор: {{ post.author.get_full_name }}
      {% else %}
        Автор: {{ post.author.username }}&nbsp;&nbsp;&nbsp;
      {% endif %}

      <a href="{% url 'posts:profile' post.author.username %}">
        <button type="button" class="btn btn-outline-secondary">
          все посты пользователя
        </button>
      </a>
    </li>
    <li class="list-group-item list-group-item-action list-group-item-light">
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <div class="card bg-light mb-3">
    <div class="card-body">
      {# Из post_detail перенесено сюда. Для превью на главной. #}
      {% thumbnail post.image "660x159" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
    </div>
  </div>

  <a href="{% url 'posts:post_detail' post.id %}">
    <button type="button" class="btn btn-outline-primary">
      подробная информация
    </button>
  </a>

  {% if post.group %}
    <a href="{% url 'posts:group_posts'  post.group.slug %}">
      <button type="button" class="btn btn-outline-primary">
        все записи группы
      </button>
    </a>
  {% endif %}
</article>

{# под последним постом нет линии #}
{% if not forloop.last %}
  <hr>
{% endif %}

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/form_error.html
<!DOCTYPE html>
{% if form.errors %} {# Загружаем фильтры #}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">{{ error|escape }}</div>
    {% endfor %}
  {% endfor %}

  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/form_field.html
<!DOCTYPE html>
{% csrf_token %}
{% load user_filters %}

{% for field in form %}
  <div class="form-group row my-3"
      {% if field.field.required %}
        aria-required="true"
      {% else %}
        aria-required="false"
      {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
      {{ field|addclass:'form-control' }}
        {% if field.help_text %}
          <small class="form-text text-muted" id="{{ field.id_for_label }}-help">
            {{ field.help_text|safe }}
          </small>
        {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/header.html
<!DOCTYPE html>
{% load static %}
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <span style="color:red">Ya</span>tube
    </a>
    {% with request.resolver_match.view_name as view_name %}
      <!-- .nav-pills нужен для выделения активных пунктов -->
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
             href="{% url 'about:author' %}">
            Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
             href="{% url 'about:tech' %}">
            Технологии
          </a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
               href="{% url 'posts:post_create' %}">
              Новая запись
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}"
               href="{% url 'users:password_change_form' %}">
              Изменить пароль
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'users:logout' %}">
              Выйти
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">
              Пользователь: {{ user.username }}
            </a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
               href="{% url 'users:login' %}">
              Войти
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
               href="{% url 'users:signup' %}">
              Регистрация
            </a>
          </li>
        {% endif %}
      </ul>
    {% endwith %}
  </div>
</nav>

yatube/templates/includes/switcher.html
<!DOCTYPE html>
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link {% if index %}active{% endif %}"
           href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}