yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('create/', views.post_create, name='post_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.delete_post, name='delete'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
else:

    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', serve,
                kwargs={'document_root': settings.STATIC_ROOT, }),
        re_path(r'^media/(?P<path>.*)$', serve,
                kwargs={'document_root': settings.MEDIA_ROOT, }),
    ]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from yatube.settings import POST_SYMBOLS, COMMENT_SYMBOLS
from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=200, blank=True)

    class Meta:
        ordering = ['title', ]

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст',
        help_text='Добавьте текст новой записи'
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name="posts",
        blank=True, null=True,
        verbose_name='Группа',
        help_text='Выберите группу для новой записи',
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:POST_SYMBOLS]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        verbose_name='Пост',
        related_name='comment',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        related_name='comment',
        on_delete=models.CASCADE
    )
    text = models.TextField(
        verbose_name='Текст',
        help_text='Прокомментировать'
    )

    class Meta:
        ordering = ['-pub_date', ]

    def __str__(self):
        return self.text[:COMMENT_SYMBOLS]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Подписчик',
        related_name='follower',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        related_name='following',
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name_plural = 'Подписки'
        verbose_name = 'Подписка'

    def __str__(self):
        return f'{self.user} подписался на {self.author}'

yatube/posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post

        fields = ('group', 'text', 'image',)

        labels = {
            'group': 'Группа',
            'text': 'Текст',
        }

        help_texts = {
            'group': 'Выберите группу для новой записи',
            'text': 'Добавьте текст для новой записи'
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment

        fields = ('text', )

        help_texts = {
            'text': 'Добавьте комментарий'
        }

yatube/posts/views.py
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Group, Follow
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

from yatube.settings import LIMIT_POSTS, CACHE_TIMEOUT
from .forms import PostForm, CommentForm


# Главная страница
@cache_page(CACHE_TIMEOUT, key_prefix='index_page')
def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()
    paginator = Paginator(posts, LIMIT_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, template, context)


# Страница с постами группы
def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group)
    paginator = Paginator(posts, LIMIT_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
        'posts': posts,
        'paginator': paginator,
    }
    return render(request, template, context)


# Все посты в профиле пользователя
def profile(request, username):

    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, LIMIT_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'author': author,
        "posts_count": author.posts.count()
    }

    if request.user.is_authenticated:
        following_exist = request.user.follower.filter(author=author).exists()
        context["following"] = following_exist

    return render(request, 'posts/profile.html', context)


# Раскрыть пост полностью
def post_detail(request, post_id):

    post = get_object_or_404(Post, pk=post_id)
    comments = post.comment.all()
    comment_form = CommentForm(request.POST or None)

    context = {
        "post": post,
        "author": post.author,
        "posts_count": post.author.posts.count(),
        'comment_form': comment_form,
        'comments': comments,
    }

    return render(request, 'posts/post_detail.html', context)


# создать новый пост
@login_required
def post_create(request):

    user = request.user
    form = PostForm(request.POST or None)

    if form.is_valid():
        post = form.save(False)
        post.author = user
        post.save()
        return redirect("posts:profile", user.username)

    context = {
        "form": form,
    }

    return render(request, "posts/post_edit.html", context)


# Отредактировать пост
@login_required
def post_edit(request, post_id):

    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    context = {
        'post': post,
        'form': form,
        'post_id': post_id,
        'is_edit': True,
    }
    if request.user == post.author and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(f'/posts/{post.id}', id=post_id)
    return render(request, 'posts/post_edit.html', context)


# Удалить пост
@login_required
def delete_post(request, post_id):
    remove_post = Post.objects.filter(pk=post_id)
    remove_post.delete()

    return redirect('posts:index')


# Добавить комментарий
@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect('posts:post_detail', post_id=post_id)


# Вывод постов, на которых подписан текущий пользователь
@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user)
    paginator = Paginator(posts, settings.LIMIT_POSTS)
    page_number = request.GET.get('page_obj')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
    }
    return render(request, 'posts/follow.html', context)


# Добавить подписку на автора
@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


# Удалить подписку на автора
@login_required
def profile_unfollow(request, username):
    user_follower = get_object_or_404(
        Follow,
        user=request.user,
        author__username=username
    )
    user_follower.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/follow.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load cache %}

{% block title %}
  На кого Вы подписаны
{% endblock %}

{% block content %}
  {% include 'includes/switcher.html' %}
  {% cache 20 follow_index_page %}
    {% for post in page_obj %}
      {% include 'includes/article.html' %}
    {% endfor %}
  {% endcache %}
  {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}

{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>

  {% for post in page_obj %}
    {% include 'includes/article.html' %}
  {% endfor %}
  {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}
  Последние обновления
{% endblock %}

{% block content %}
  {% include 'includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/article.html' %}
  {% endfor %}

  {% include 'posts/paginator.html' %}

{% endblock %}

yatube/templates/posts/paginator.html
<!DOCTYPE html>
<!-- Отрисовываем навигацию паджинатора только если все посты не помещаются на первую страницу -->
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <span class="page-link">{{ i }}</span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/posts/post_comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ comment_form.text|addclass:'form-control' }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}

yatube/templates/posts/post_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_posts' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
          <li class="list-group-item">
            {% if post.author.get_full_name %}
              Автор: {{ post.author.get_full_name }}
            {% else %}
              Автор: {{ post.author.username }}&nbsp;&nbsp;&nbsp;
            {% endif %}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
     {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}" alt="{{ post.title }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      {% if user == post.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          Редактировать запись
        </a>
        <a class="btn btn-secondary" href="{% url 'posts:delete' post.id %}">Удалить запись</a>
      {% endif %}

      {% if post.comments.exists %}
        <div>
          Комментариев: {{ post.comments.count }}
        </div>
      {% endif %}

      {% if user.is_authenticated %}
        {% include 'posts/post_comment.html' %}
      {% endif %}

    </article>
  </div>
{% endblock %}

yatube/templates/posts/post_edit.html
{% extends "base.html" %}

{% block title %}
  Редактировать запись
{% endblock %}

{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Редактировать запись</div>
      <div class="card-body">

        {% include 'includes/form_error.html' %}

        <form method="post" enctype="multipart/form-data">
            <div
                class="form-group row"
                {% if field.field.required %}
                  aria-required="true"
                {% else %}
                  aria-required="false"
                {% endif %}
            >

            {% include 'includes/form_field.html' %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сохранить
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}
  Профайл пользователя {{ author.username }}
{% endblock %}

{% block content %}
  <div class="mb-5">
    <h2>Все посты пользователя {{ author.username }}&nbsp;&nbsp;&nbsp;
      {% if following %}
        <a class="d-inline p-2 btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a class="d-inline p-2 btn btn-lg btn-primary"
           href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    </h2>
    <h5>Всего постов: {{ author.posts.count }}</h5>
  </div>


  {% for post in page_obj %}
    {% include 'includes/article.html' %}
  {% endfor %}

  {% include 'posts/paginator.html' %}

{% endblock %}