yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
# Импортируем из приложения django.contrib.auth нужный view-класс
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordResetView
)
from django.urls import path
from . import views


app_name = 'users'


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
else:

    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', serve,
                kwargs={'document_root': settings.STATIC_ROOT, }),
        re_path(r'^media/(?P<path>.*)$', serve,
                kwargs={'document_root': settings.MEDIA_ROOT, }),
    ]

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


# класс для формы регистрации.
# Он является наследником предустановленного класса UserCreationForm.
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
# Импортируем CreateView, чтобы создать ему наследника
from django.views.generic import CreateView


# Функция reverse_lazy позволяет получить URL по параметрам функции path()
# Берём, тоже пригодится
from django.urls import reverse_lazy


# Импортируем класс формы, чтобы сослаться на неё во view-классе
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}
  Вы вышли из системы
{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/login.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block title %}
  Войти
{% endblock %}

{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}

            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

          <form method="post"
                {% if action_url %}
                action="{% url action_url %}"
                {% endif %}
          >
            {% csrf_token %}

            {% for field in form %}
            <div class="form-group row my-3"
                 {% if field.field.required %}
                 aria-required="true"
                 {% else %}
                 aria-required="false"
                 {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                <span class="required text-danger">*</span>
                {% endif %}
              </label>
              <div>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
                {% endif %}
              </div>
            </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
                Забыли пароль?
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_change_done.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block title %}
  Пароль изменён
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Пароль изменён</div>
        <div class="card-body">
          <p>Пароль успешно изменён</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_change_form.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block title %}
  Изменение пароля
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Изменить пароль</div>
        <div class="card-body">

          {% include 'includes/form_error.html' %}

          <form method="post"
              {% if action_url %}
                action="{% url action_url %}"
              {% endif %}
          >

            {% include 'includes/form_field.html' %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>

          </form>

        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block title %}
  Изменение пароля
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Сброс пароля выполнен</div>
        <div class="card-body">
          <p>Пароль успешно изменён.</p>
          <a href="{% url 'users:login' %}">Войти</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block title %}
  Новый пароль
{% endblock %}

{% block content %}
  {% if validlink %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Введите новый пароль</div>
          <div class="card-body">

          {% include 'includes/form_error.html' %}

            <form method="post"
                {% if action_url %}
                  action="{% url action_url %}"
                {% endif %}
            >

              {% include 'includes/form_field.html' %}

              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Назначить новый пароль
                </button>
              </div>

            </form>

          </div>
        </div>
      </div>
    </div>
  {% else %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Ошибка</div>
          <div class="card-body">
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

yatube/templates/users/password_reset_done.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block title %}
  Пароль изменён
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Ссылка на восстановление пароля отправлена</div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля.</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_form.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}
  Сброс пароля
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты
        </div>

        <div class="card-body">

          {% include 'includes/form_error.html' %}

          <form method="post" action="{% url 'users:password_reset_form' %}">

            {% include 'includes/form_field.html' %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>

          </form>

        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/signup.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block title %}
  Зарегистрироваться
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
        <div class="card-body">

          {% include 'includes/form_error.html' %}

          <form method="post" action="{% url 'users:signup' %}">

            {% include 'includes/form_field.html' %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>

          </form>

        </div>
      </div>
    </div>
  </div>
{% endblock %}